/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.guikar.netbeans.ufc.poo.mvc;

/**
 *
 * @author Guilherme
 */
public class TelaPlacar extends javax.swing.JFrame implements Observer{

    private Placar model;
    private TelaPlacarController controller;
    
    public TelaPlacar(Placar model) {
        initComponents();
        setVisible(true);
        if(model!=null)
            this.model=model;
        model.addObserver(this);
        this.controller=new TelaPlacarController(model,this);
    }

    public void setLblP1(String pontos) {
        this.lblP1.setText(pontos);
    }

    public void setLblP2(String pontos) {
        this.lblP2.setText(pontos);
    }

    public void setLblTime1(String time) {
        this.lblTime1.setText(time);
    }

    public void setLblTime2(String time) {
        this.lblTime2.setText(time);
    }
    
    @Override
    public void update() {
        setLblTime1(model.getTime(1));
        setLblTime2(model.getTime(2));
        setLblP1(Integer.toString(model.getPontos(1)));
        setLblP2(Integer.toString(model.getPontos(2)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        lblP1 = new javax.swing.JLabel();
        lblTime1 = new javax.swing.JLabel();
        lblP2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("X");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        lblTime2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTime2.setText("Time2");
        getContentPane().add(lblTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        lblP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblP1.setText("P1");
        getContentPane().add(lblP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        lblTime1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTime1.setText("Time1");
        getContentPane().add(lblTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblP2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblP2.setText("P2");
        getContentPane().add(lblP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel lblTime2;
    // End of variables declaration//GEN-END:variables
}
