/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.guikar.netbeans.ufc.poo.mvc;

/**
 *
 * @author Guilherme
 */
public class TelaPrincipalConfiguracao extends javax.swing.JFrame implements Observer{

    private Placar model;
    private TelaPrincipalConfiguracaoController controller;
    
    public TelaPrincipalConfiguracao(Placar model) {
        initComponents();
        if(model!=null)
            this.model=model;
        this.controller=new TelaPrincipalConfiguracaoController(model, this);
    }

    public String getTxtTime1() {
        return txtTime1.getText();
    }

    public String getTxtTime2() {
        return txtTime2.getText();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLimparTimes = new javax.swing.JButton();
        txtTime1 = new javax.swing.JTextField();
        txtTime2 = new javax.swing.JTextField();
        btnTime1 = new javax.swing.JButton();
        btnTime2 = new javax.swing.JButton();
        btnAddTimes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(300, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Time 2:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setText("Time 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnLimparTimes.setText("Limpar Times");
        getContentPane().add(btnLimparTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, -1));
        getContentPane().add(txtTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, -1));
        getContentPane().add(txtTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, -1));

        btnTime1.setText("Aumentar Placar 1");
        btnTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTime1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        btnTime2.setText("Aumentar Placar 2");
        btnTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTime2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        btnAddTimes.setText("Adicionar Times");
        btnAddTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTimesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTimesActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnAddTimesActionPerformed

    private void btnTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTime1ActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnTime1ActionPerformed

    private void btnTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTime2ActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnTime2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTimes;
    private javax.swing.JButton btnLimparTimes;
    private javax.swing.JButton btnTime1;
    private javax.swing.JButton btnTime2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtTime1;
    private javax.swing.JTextField txtTime2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {}
}
