/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.guikar.ufc.poo.termometro.view;

import br.com.guikar.ufc.poo.termometro.controller.ConfiguraClimaController;
import br.com.guikar.ufc.poo.termometro.model.Cidade;
import br.com.guikar.ufc.poo.termometro.model.Observer;

import javax.swing.*;
import java.text.DecimalFormat;

/**
 *
 * @author Guilherme
 */
public class ConfiguraClima extends javax.swing.JFrame implements Observer{

    private Cidade model;
    private ConfiguraClimaController controller;
    private ButtonGroup tipoTempRadio = new ButtonGroup();
    private ButtonGroup tipoClimaRadio = new ButtonGroup();
    public ConfiguraClima() {
        initComponents();
    }
    
    public ConfiguraClima(Cidade model) {
        this();
        if(model!=null){
            this.model = model;
            this.model.addObserver(this);
        }
        controller=new ConfiguraClimaController(this, this.model);
    }
    
    public String getCidade(){
        return txtCidade.getText();
    }

    public void setTxtCidade(String txtCidade) {
        this.txtCidade.setText(txtCidade);
    }
    public String getUf(){
        return txtUf.getText();
    }    
    public void setTxtUf(String txtUf) {
        this.txtUf.setText(txtUf);
    }
    public float getTemperatura(){
        try{
            return Float.parseFloat(txtTemp.getText());
        }catch(Exception e){
            return 0f;
        }
    }
    public void setTxtTemp(String txtTemp) {
        DecimalFormat df = new DecimalFormat("0.##");
        this.txtTemp.setText(df.format(Double.parseDouble(txtTemp)));
    }
    public int getTipoTemperatura(){
        return radioC.isSelected()?0:1;
    }
    public void setTipoTemperatura(int tTemp) {
        if(tTemp==0){
            radioC.setSelected(true);
            radioF.setSelected(false);
        }else{
            radioC.setSelected(false);
            radioF.setSelected(true);
        }
    }
    public int getTipoClima(){
        return radioSol.isSelected()?0:radioChuva.isSelected()?1:2;
    }
    public void setTipoClima(int tClima){
        switch (tClima) {
            case 0:
                radioSol.setSelected(true);
                radioChuva.setSelected(false);
                radioNublado.setSelected(false);
                break;
            case 1:
                radioSol.setSelected(false);
                radioChuva.setSelected(true);
                radioNublado.setSelected(false);
                break;
            case 2:
                radioSol.setSelected(false);
                radioChuva.setSelected(false);
                radioNublado.setSelected(true);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radioC = new javax.swing.JRadioButton();
        radioF = new javax.swing.JRadioButton();
        txtCidade = new JTextField();
        txtUf = new JTextField();
        txtTemp = new JTextField();
        radioSol = new javax.swing.JRadioButton();
        radioChuva = new javax.swing.JRadioButton();
        radioNublado = new javax.swing.JRadioButton();
        btnAddTerm = new javax.swing.JButton();
        btnAddTermClima = new javax.swing.JButton();
        btnAddCidade = new javax.swing.JButton();
        btnAumentar = new javax.swing.JButton();
        btnDiminuir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configura Clima");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cidade:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Temperatura:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setText("Tipo Temperatura:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setText("Clima:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setText("UF:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        tipoTempRadio.add(radioC);
        radioC.setSelected(true);
        radioC.setText("ºC");
        getContentPane().add(radioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        tipoTempRadio.add(radioF);
        radioF.setText("ºF");
        getContentPane().add(radioF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, -1));
        getContentPane().add(txtUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 120, -1));
        getContentPane().add(txtTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, -1));

        tipoClimaRadio.add(radioSol);
        radioSol.setSelected(true);
        radioSol.setText("Sol");
        getContentPane().add(radioSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        tipoClimaRadio.add(radioChuva);
        radioChuva.setText("Chuva");
        getContentPane().add(radioChuva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        tipoClimaRadio.add(radioNublado);
        radioNublado.setText("Nublado");
        getContentPane().add(radioNublado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        btnAddTerm.setText("Adicionar Termometro");
        btnAddTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTermActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddTerm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 210, -1));

        btnAddTermClima.setText("Adicionar Termometro Clima");
        btnAddTermClima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTermClimaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddTermClima, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 210, -1));

        btnAddCidade.setText("Adicionar Cidade");
        btnAddCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        btnAumentar.setText("Diminuir Temperatura");
        btnAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 210, -1));

        btnDiminuir.setText("Aumentar Temperatura");
        btnDiminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiminuirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiminuir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 210, -1));

        btnAtualizar.setText("Atualizar Informações Cidade ");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 210, -1));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnAumentarActionPerformed

    private void btnAddCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCidadeActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnAddCidadeActionPerformed

    private void btnAddTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTermActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnAddTermActionPerformed

    private void btnAddTermClimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTermClimaActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnAddTermClimaActionPerformed

    private void btnDiminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiminuirActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnDiminuirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCidade;
    private javax.swing.JButton btnAddTerm;
    private javax.swing.JButton btnAddTermClima;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnAumentar;
    private javax.swing.JButton btnDiminuir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton radioC;
    private javax.swing.JRadioButton radioChuva;
    private javax.swing.JRadioButton radioF;
    private javax.swing.JRadioButton radioNublado;
    private javax.swing.JRadioButton radioSol;
    private JTextField txtCidade;
    private JTextField txtTemp;
    private JTextField txtUf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        int tipoTemp="ºC".equals(model.getTipoTemperatura())?0:1;
        float temperatura;
        setTxtCidade(model.getNome());
        setTxtUf(model.getUf());
        setTipoTemperatura(tipoTemp);
        setTipoClima("sol".equals(model.getClima())?0:"chuva".equals(model.getClima())?1:2);
        if(tipoTemp==0)
            temperatura=model.getTemperatura();
        else
            temperatura= (float) ((model.getTemperatura()-32)/1.8);
        setTxtTemp(String.valueOf(temperatura));
    }
}
