/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.guikar.ufc.poo.termometro.view;

import br.com.guikar.ufc.poo.termometro.controller.TermometroCidadeController;
import br.com.guikar.ufc.poo.termometro.model.Cidade;
import br.com.guikar.ufc.poo.termometro.model.Observer;
import java.text.DecimalFormat;

/**
 *
 * @author Guilherme
 */
public class TermometroCidade extends javax.swing.JFrame implements Observer{
    private Cidade model;
    private TermometroCidadeController controller;
    /**
     * Creates new form TermometroCidade
     */
    public TermometroCidade(Cidade model) {
        initComponents();
        if(model!=null)
            this.model=model;
        model.addObserver(this);
        controller=new TermometroCidadeController(model, this);
    }

    public void setLblCidade(String lblCidade) {
        this.lblCidade.setText(lblCidade);
    }

    public void setLblTemp(String lblTemp) {
        DecimalFormat df = new DecimalFormat("0.##");
        this.lblTemp.setText(df.format(Double.parseDouble(lblTemp)));
    }

    public void setLblTipo(String lblTipo) {
        this.lblTipo.setText(lblTipo);
    }

    public void setLblUf(String lblUf) {
        this.lblUf.setText(lblUf);
    }
    public void setLblImagem(String lblImagem){
        this.lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/guikar/ufc/poo/termometro/imagens/"+lblImagem+".png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblUf = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cidade");
        jFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, -1, -1));

        jLabel2.setText("-");
        jFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 11, -1, -1));

        jLabel3.setText("UF");
        jFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, -1, -1));

        jLabel4.setText("0");
        jFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel5.setText("ºC");
        jFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Termometro Clima");
        setMinimumSize(new java.awt.Dimension(500, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/guikar/ufc/poo/termometro/imagens/sol.png"))); // NOI18N
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 210));

        lblCidade.setText("Cidade");
        getContentPane().add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jLabel6.setText("-");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        lblUf.setText("UF");
        getContentPane().add(lblUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        lblTemp.setText("0");
        getContentPane().add(lblTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        lblTipo.setText("ºC");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        setLblCidade(model.getNome());
        setLblTemp(String.valueOf(model.getTemperatura()));
        setLblTipo(model.getTipoTemperatura());
        setLblUf(model.getUf());
        setLblImagem(model.getClima());
    }
}
