/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.guikar.jmf.logica_desafios_e_testes.classes;

/**
 *
 * @author Guilherme
 */
public class AdivinhaSwing extends javax.swing.JFrame {

    /**
     * Creates new form AdivinhaSwing
     */
    public AdivinhaSwing() {
//        initComponents();
        lblNum.setVisible(false);
        txtNum.setVisible(false);
        botao=0;
    }
    private static int botao;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMuda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMuda = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        lblNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMuda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMuda.setText("<html>Leitor de Pensamento!</html>");
        getContentPane().add(lblMuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/guikar/logica/desafios_e_testes/imagens/balao.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/guikar/logica/desafios_e_testes/imagens/genio.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        btnMuda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnMuda.setText("Começar");
        btnMuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, -1));

        txtNum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 80, -1));

        lblNum.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNum.setText("Digite o numero Pensado:");
        getContentPane().add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    private void btnMudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMudaActionPerformed
        botao++;
        int num,res;
        if(botao==1){
            btnMuda.setText("Proximo");
            lblMuda.setText("Pense em um numero!");
        }if(botao==2){
            btnMuda.setText("Proximo");
            lblMuda.setText("Multiplique por 2!");
        }if(botao==3){
            btnMuda.setText("Proximo");
            lblMuda.setText("Some 6!");
        }if(botao==4){
            btnMuda.setText("Digitar o numero!");
            lblMuda.setText("Divida por 2!");
        }if(botao==5){
            lblNum.setVisible(true);
            txtNum.setVisible(true);
            txtNum.setText("");
            lblMuda.setText("<html>Descobrindo o numero pensado!</html>");
            btnMuda.setText("Verificar");
        }if(botao==6){
            num=Integer.parseInt(txtNum.getText());
            res=(num*2-6)/2;
            lblNum.setVisible(false);
            txtNum.setVisible(false);
            lblMuda.setText("<html>O numero pensado foi "+Integer.toString(res)+ "!</html>");
            btnMuda.setText("Recomeçar");
        }if(botao==7){
            botao=0;
            btnMuda.setText("Começar");
            lblMuda.setText("<html>Leitor de Pensamento!</html>");
        }
    }//GEN-LAST:event_btnMudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdivinhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdivinhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdivinhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdivinhaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdivinhaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMuda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMuda;
    private javax.swing.JLabel lblNum;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
