package br.com.guikar.eclusa.view;

import br.com.guikar.eclusa.controller.GerenciamentoEclusaController;
import br.com.guikar.eclusa.model.Eclusa;

import javax.swing.*;

public class GerenciamentoEclusaView extends JFrame{

    private GerenciamentoEclusaController controller;
    private Eclusa model;
    private DefaultListModel lista= new DefaultListModel();
    public GerenciamentoEclusaView(Eclusa model) {
        initComponents();
        if (model != null)
            this.model = model;
        controller = new GerenciamentoEclusaController(this, model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLargura = new JLabel();
        lblComprimento = new JLabel();
        lblVazao = new JLabel();
        lblCapMax = new JLabel();
        lblCapMin = new JLabel();
        lblEclusa = new JLabel();
        txtLargura = new JFormattedTextField();
        txtComprimento = new JFormattedTextField();
        txtVazao = new JFormattedTextField();
        txtCapMax = new JFormattedTextField();
        txtCapMin = new JFormattedTextField();
        btnIniEclusa = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eclusa");
        setPreferredSize(new java.awt.Dimension(410, 310));
        setResizable(false);
        setSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLargura.setHorizontalAlignment(SwingConstants.CENTER);
        lblLargura.setText("Largura:");
        getContentPane().add(lblLargura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 20));

        lblComprimento.setHorizontalAlignment(SwingConstants.CENTER);
        lblComprimento.setText("Comprimento:");
        getContentPane().add(lblComprimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 20));

        lblVazao.setHorizontalAlignment(SwingConstants.CENTER);
        lblVazao.setText("Vazão:");
        getContentPane().add(lblVazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 20));

        lblCapMax.setHorizontalAlignment(SwingConstants.CENTER);
        lblCapMax.setText("Capacidade Maxima:");
        getContentPane().add(lblCapMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 20));

        lblCapMin.setHorizontalAlignment(SwingConstants.CENTER);
        lblCapMin.setText("Capacidade Minima:");
        getContentPane().add(lblCapMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 20));

        lblEclusa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEclusa.setText("Eclusa");
        getContentPane().add(lblEclusa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtLargura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtLargura.setHorizontalAlignment(JTextField.LEFT);
        getContentPane().add(txtLargura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, 20));

        txtComprimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtComprimento.setHorizontalAlignment(JTextField.LEFT);
        getContentPane().add(txtComprimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 210, 20));

        txtVazao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtVazao.setHorizontalAlignment(JTextField.LEFT);
        getContentPane().add(txtVazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 210, 20));

        txtCapMax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCapMax.setHorizontalAlignment(JTextField.LEFT);
        getContentPane().add(txtCapMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 210, 20));

        txtCapMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCapMin.setHorizontalAlignment(JTextField.LEFT);
        getContentPane().add(txtCapMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 210, 20));

        btnIniEclusa.setText("<html><p style=\"text-align:center;\">Iniciar Eclusa</p></html>");
        btnIniEclusa.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnIniEclusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniEclusaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniEclusa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 350, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniEclusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniEclusaActionPerformed
        controller.acao(evt);
    }//GEN-LAST:event_btnIniEclusaActionPerformed

    public DefaultListModel getLista() {
        return lista;
    }

    public float getTxtComprimento() {
        try {
            return Float.parseFloat(txtComprimento.getText().replace(',', '.'));
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Valor da Altura deve ser um numero","Erro",JOptionPane.ERROR_MESSAGE);
            return 0f;
        }
    }

    public float getTxtCapMax() {
        try {
            return Float.parseFloat(txtCapMax.getText().replace(',', '.'));
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Valor da Capacidade Maxima deve ser um numero","Erro",JOptionPane.ERROR_MESSAGE);
            return 0f;
        }
    }

    public float getTxtCapMin() {
        try {
            return Float.parseFloat(txtCapMin.getText().replace(',', '.'));
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Valor da Capacidade Minima deve ser um numero","Erro",JOptionPane.ERROR_MESSAGE);
            return 0f;
        }
    }

    public float getTxtLargura() {
        try {
            return Float.parseFloat(txtLargura.getText().replace(',', '.'));
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Valor da Largura deve ser um numero","Erro",JOptionPane.ERROR_MESSAGE);
            return 0f;
        }
    }

    public float getTxtVazao() {
        try {
            return Float.parseFloat(txtVazao.getText().replace(',', '.'));
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Valor da Vazao deve ser um numero","Erro",JOptionPane.ERROR_MESSAGE);
            return 0f;
        }
    }

    public void setTxtCapMax(String txtCapMax) {
        this.txtCapMax.setText(txtCapMax.replace('.', ','));
    }

    public void setTxtCapMin(String txtCapMin) {
        this.txtCapMin.setText(txtCapMin.replace('.', ','));
    }

    public void setTxtComprimento(String txtComprimento) {
        this.txtComprimento.setText(txtComprimento.replace('.', ','));
    }

    public void setTxtLargura(String txtLargura) {
        this.txtLargura.setText(txtLargura.replace('.', ','));
    }

    public void setTxtVazao(String txtVazao) {
        this.txtVazao.setText(txtVazao.replace('.', ','));
    }
    
    

    public void setBtnIniEclusa(String btnIniEclusa) {
        this.btnIniEclusa.setText(btnIniEclusa);
    }
    
    
    
    public void mensagem(String titulo, String mensagem, int tipo){
        JOptionPane.showMessageDialog(this,mensagem,titulo,tipo);
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnIniEclusa;
    private JLabel lblCapMax;
    private JLabel lblCapMin;
    private JLabel lblComprimento;
    private JLabel lblEclusa;
    private JLabel lblLargura;
    private JLabel lblVazao;
    private JFormattedTextField txtCapMax;
    private JFormattedTextField txtCapMin;
    private JFormattedTextField txtComprimento;
    private JFormattedTextField txtLargura;
    private JFormattedTextField txtVazao;
    // End of variables declaration//GEN-END:variables
}
